"""Regeneration migration initiale complete

Revision ID: 5d86792d557e
Revises: 
Create Date: 2025-10-30 22:42:07.449254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d86792d557e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('measure_timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sunrise_time', sa.String(), nullable=True),
    sa.Column('sunset_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_records_id'), 'weather_records', ['id'], unique=False)
    op.create_index(op.f('ix_weather_records_location_name'), 'weather_records', ['location_name'], unique=False)
    op.create_index('weather_record_idx', 'weather_records', ['location_name', 'measure_timestamp'], unique=False)
    op.create_table('air_pollution_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('no', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('nh3', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['weather_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_pollution_records')
    op.drop_index('weather_record_idx', table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_location_name'), table_name='weather_records')
    op.drop_index(op.f('ix_weather_records_id'), table_name='weather_records')
    op.drop_table('weather_records')
    # ### end Alembic commands ###
